### ISSUE TITLE
symfony-swoole/swoole-bundle

### ISSUE THREAD

**Issue by pistej** [swoole/awesome-swoole#12]
Hi, I would like to suggest better bundle/fw. integration for symfony, than: pixelfederation/swoole-bundle

URL: https://github.com/symfony-swoole/swoole-bundle

Newer, maintained bundle, with support for latest Symfony and for booth Swoole and Open Swoole.

Thx, or should I create PR ?

**Comment by deminy** [comment]
Package replaced. Thanks for the suggestion.
